### ISSUE TITLE
[BUG] runtime.KeepAlive doesn't ensure that the memory address will remain the same

### ISSUE THREAD

**Issue by dshulyak** [hodgesds/iouring-go#10]
Hi there, I just checked if you were doing any more work on uring library.
And found this commit https://github.com/hodgesds/iouring-go/commit/bf9ad57e7a1dbcc0aa65b46d2278ed78d0b9d34c and in particular following snippet catched my eye:

```go
func (r *Ring) Send(
	fd int,
	b []byte,
	flags uint8,
) error {
	id, err := r.PrepareSend(fd, b, flags)
	if err != nil {
		return err
	}
	errno, _ := r.complete(id)
	// No GC until the request is done.
	runtime.KeepAlive(b)
	if errno < 0 {
		return syscall.Errno(-errno)
	}
	return nil
}
```

The problem with runtime.KeepAlive here is that while it ensures that `b` is not garbage collected, it doesn't guarantee that `b` memory address will remain the same while the submission is in progress. In PrepareSend you must convert golang pointer to uintptr and use it in submission entry, however that uintptr will often change during submission lifetime.

The only way to ensure that the address doesn't change for an arbitrary pointer is to use `uintptrescapes` pragma, otherwise your submissions will fail in very unexpected ways. See the thread and in particular this comment https://github.com/golang/go/issues/16035#issuecomment-225452371

**Comment by hodgesds** [comment]
It may depend if `b` is stack allocated or heap allocated. I asked about heap allocated values in [40431](https://github.com/golang/go/issues/40431) and with the current runtime the memory address should be stable. However, you bring up a good point and I'll take a look at this. I haven't had much time to work on this as I've been rather busy with work and finishing up some other projects.

I'm to the point in this library where there's several things I'd like to get around to and change and may end up just rewriting parts of it. Thanks again for bringing this up and I'll try to take a look at it soon.!

**Comment by dshulyak** [comment]
thats good to know. i was suspecting that memory address will change whenever stack grows or shrinks, but wasn't sure about gc. anyway, that's not something that can be safely assumed in the library. cheers
